### ISSUE TITLE
MQTT reporting erroneous JSON with 0.8.9

### ISSUE THREAD

**Issue by ScratMan** [vingerha/gazpar_2_mqtt#20]
---
name: Bug report
title: 'MQTT reporting erroneous JSON with 0.8.9'

---
**Which type of installation/run**
- container (docker compose)

**Your configuration**
```yaml
version: '3.5'
services:
  gazpar2mqtt:
    container_name: gazpar_2_mqtt
    image: vingerha/gazpar_2_mqtt:latest
    tty: true
    restart: unless-stopped
    environment:
      # obligatoire :
      GRDF_USERNAME: *******
      GRDF_PASSWORD: *******
      MQTT_HOST: 192.168.1.29
      TZ: Europe/Paris
      STANDALONE_MODE: 'True'
      # facultatif
      MQTT_PORT: 1883
      MQTT_TOPIC: gazpar
      MQTT_CLIENTID: grdf
      MQTT_USERNAME: *******
      MQTT_PASSWORD: *******
      HASS_DISCOVERY: 'True'
      HASS_PREFIX: 'homeassistant'
      HASS_DEVICE_NAME: 'gazpar'
      HASS_LTS: 'True'
      SCHEDULE_TIME: 06:30
    volumes:
      - ./:/data
      - ./app:/app
```

**Describe the bug**
When starting the gazpar_2_mqtt container using 0.8.9, it creates a warning in Home Assistant logs about erroneous JSON received by MQTT.
Stop the container, switch to `vingerha/gazpar_2_mqtt:0.8.8` and the issue disappears.

**Additional**
MQTT error appears in Home Assistant logs (I masked sensitive data with *):

> Enregistreur: homeassistant.components.mqtt.entity
> Source: components/mqtt/entity.py:432
> intégration: MQTT (documentation, problèmes)
> S'est produit pour la première fois: 00:40:54 (1 occurrences)
> Dernier enregistrement: 00:40:54
> 
> Erroneous JSON: {'pce_alias': 'Maison', 'pce_id': '19**********85', 'freqence': None, 'activation_date ': datetime.datetime(2024, **, *, 23, 9, 22), 'owner_name': 'B**', 'postal_code': '38***'}
>
