### ISSUE TITLE
Docker image : ModuleNotFoundError: No module named 'param'

### ISSUE THREAD

**Issue by davidXire** [vingerha/gazpar_2_mqtt#21]
---
name: Bug report
title: 'Docker image : ModuleNotFoundError: No module named 'param''

---
**Which type of installation/run**
- docker-compose

**Your configuration**

```
version: '3.5'
services:
  gazpar2mqtt:
    container_name: gazpar_2_mqtt
    image: vingerha/gazpar_2_mqtt:latest
    tty: true
    restart: unless-stopped
    environment:
      # obligatoire :
      GRDF_USERNAME: ***
      GRDF_PASSWORD: *
      MQTT_HOST: 192.168.1.3*
      TZ: Europe/Paris
      STANDALONE_MODE: 'True'
      # facultatif
      MQTT_PORT: 1883
      MQTT_TOPIC: gazpar
      MQTT_USERNAME: *
      MQTT_PASSWORD: *
      HASS_DISCOVERY: 'True'
      HASS_PREFIX: 'homeassistant'
      HASS_DEVICE_NAME: 'gazpar'
      HASS_LTS: 'True'
      SCHEDULE_TIME: 06:30
    volumes:
      - ./data:/data
      - ./data/app:/app

```

**Describe the bug**
container won't start

Steps/data to reproduce the behavior, e.g.
Take a fresh docker compose configuration and start

**Additional**

```
gazpar_2_mqtt  | Traceback (most recent call last):
gazpar_2_mqtt  |   File "//app/gazpar2mqtt.py", line 15, in <module>
gazpar_2_mqtt  |     import param
gazpar_2_mqtt  | ModuleNotFoundError: No module named 'param'
gazpar_2_mqtt exited with code 1
```
